drop table if exists users;
create table users
(
    id           bigint       not null
        primary key generated by default as identity,
    lastname     varchar(200) not null,
    name         varchar(50)  not null,
    patronymic   varchar(200) not null,
    birthday     date         not null,
    email        varchar(200) not null,
    phone_number varchar(12)  not null
);

alter table users
    owner to postgres;

create unique index unique_email
    on users (email);